# Generated by Django 5.0.1 on 2024-02-03 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concretediscipline',
            fields=[
                ('description', models.CharField(blank=True, db_column='Description', max_length=250, null=True)),
                ('id_conc_disc', models.AutoField(db_column='Id_conc_disc', primary_key=True, serialize=False)),
                ('date_reg', models.DateField(db_column='Date_reg')),
                ('id_user', models.IntegerField(blank=True, db_column='Id_user', null=True)),
            ],
            options={
                'db_table': 'ConcreteDiscipline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=80)),
                ('id_dep', models.AutoField(db_column='Id_dep', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('id_diff', models.AutoField(db_column='Id_diff', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Difficulty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=80)),
                ('id_disc', models.AutoField(db_column='Id_disc', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Discipline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=80)),
                ('id_fac', models.AutoField(db_column='Id_fac', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('id_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('id_type', models.AutoField(db_column='Id_type', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('surname', models.CharField(db_column='Surname', max_length=30)),
                ('name', models.CharField(db_column='Name', max_length=15)),
                ('second_name', models.CharField(blank=True, db_column='Second_Name', max_length=30, null=True)),
                ('email', models.CharField(db_column='Email', max_length=60)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=12, null=True)),
                ('login', models.CharField(db_column='Login', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=100)),
                ('reg_date', models.DateField(db_column='Reg_date')),
                ('id_user', models.AutoField(db_column='Id_user', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('id_chap', models.AutoField(db_column='Id_chap', primary_key=True, serialize=False)),
                ('id_disc', models.IntegerField(db_column='Id_disc')),
                ('id_conc_disc', models.ForeignKey(db_column='Id_conc_disc', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.concretediscipline')),
            ],
            options={
                'db_table': 'Chapter',
                'managed': True,
                'unique_together': {('id_chap', 'id_conc_disc', 'id_disc')},
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=60)),
                ('id_dir', models.AutoField(db_column='Id_dir', primary_key=True, serialize=False)),
                ('id_dep', models.ForeignKey(db_column='Id_dep', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.department')),
                ('id_fac', models.ForeignKey(db_column='Id_fac', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.faculty')),
            ],
            options={
                'db_table': 'Direction',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='concretediscipline',
            name='id_dir',
            field=models.ForeignKey(db_column='Id_dir', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.direction'),
        ),
        migrations.AddField(
            model_name='concretediscipline',
            name='id_disc',
            field=models.ForeignKey(db_column='Id_disc', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.discipline'),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=200, null=True)),
                ('date_reg', models.DateField(db_column='Date_reg')),
                ('id_forum', models.AutoField(db_column='Id_forum', primary_key=True, serialize=False)),
                ('id_disc', models.IntegerField(blank=True, db_column='Id_disc', null=True)),
                ('id_conc_disc', models.ForeignKey(db_column='Id_conc_disc', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.concretediscipline')),
                ('id_user', models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.user')),
            ],
            options={
                'db_table': 'Forum',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id_lec', models.AutoField(db_column='Id_lec', primary_key=True, serialize=False)),
                ('id_dep', models.ForeignKey(db_column='Id_dep', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.department')),
                ('id_user', models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.user')),
            ],
            options={
                'db_table': 'Lecturer',
                'managed': True,
                'unique_together': {('id_lec', 'id_user')},
            },
        ),
        migrations.AddField(
            model_name='concretediscipline',
            name='id_lec',
            field=models.ForeignKey(db_column='Id_lec', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.lecturer'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_stud', models.AutoField(db_column='Id_stud', primary_key=True, serialize=False)),
                ('id_dir', models.ForeignKey(db_column='Id_dir', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.direction')),
                ('id_user', models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.user')),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
                'unique_together': {('id_stud', 'id_user')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id_test', models.AutoField(db_column='Id_test', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=80)),
                ('date_reg', models.DateField(db_column='Date_reg')),
                ('date_change', models.DateField(blank=True, db_column='Date_change', null=True)),
                ('id_disc', models.IntegerField(blank=True, db_column='Id_disc', null=True)),
                ('id_user', models.IntegerField(blank=True, db_column='Id_user', null=True)),
                ('id_conc_disc', models.ForeignKey(db_column='Id_conc_disc', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.concretediscipline')),
                ('id_lec', models.ForeignKey(db_column='Id_lec', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.lecturer')),
            ],
            options={
                'db_table': 'Test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id_res', models.AutoField(db_column='Id_res', primary_key=True, serialize=False)),
                ('rating', models.CharField(db_column='Rating', max_length=25)),
                ('date_reg', models.DateField(db_column='Date_reg')),
                ('id_user', models.IntegerField(blank=True, db_column='Id_user', null=True)),
                ('id_user1', models.IntegerField(blank=True, db_column='Id_user1', null=True)),
                ('id_lec', models.ForeignKey(db_column='Id_lec', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.lecturer')),
                ('id_stud', models.ForeignKey(db_column='Id_stud', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.student')),
                ('id_test', models.ForeignKey(db_column='Id_test', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.test')),
            ],
            options={
                'db_table': 'Result',
                'managed': True,
                'unique_together': {('id_res', 'id_test')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_tick', models.AutoField(db_column='Id_tick', primary_key=True, serialize=False)),
                ('date_reg', models.DateField(db_column='Date_reg')),
                ('date_change', models.DateField(blank=True, db_column='Date_change', null=True)),
                ('id_disc', models.IntegerField(blank=True, db_column='Id_disc', null=True)),
                ('id_conc_disc', models.ForeignKey(db_column='Id_conc_disc', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.concretediscipline')),
            ],
            options={
                'db_table': 'Ticket',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='test',
            name='id_tick',
            field=models.ForeignKey(db_column='Id_tick', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.ticket'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=80)),
                ('id_top', models.AutoField(db_column='Id_top', primary_key=True, serialize=False)),
                ('id_conc_disc', models.IntegerField(db_column='Id_conc_disc')),
                ('id_disc', models.IntegerField(db_column='Id_disc')),
                ('id_chap', models.ForeignKey(db_column='Id_chap', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.chapter')),
            ],
            options={
                'db_table': 'Topic',
                'managed': True,
                'unique_together': {('id_top', 'id_chap', 'id_conc_disc', 'id_disc')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('question', models.CharField(db_column='Question', max_length=1000)),
                ('id_task', models.AutoField(db_column='Id_task', primary_key=True, serialize=False)),
                ('id_chap', models.IntegerField(db_column='Id_chap')),
                ('id_conc_disc', models.IntegerField(db_column='Id_conc_disc')),
                ('id_disc', models.IntegerField(db_column='Id_disc')),
                ('id_diff', models.ForeignKey(db_column='Id_diff', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.difficulty')),
                ('id_top', models.ForeignKey(db_column='Id_top', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.topic')),
                ('id_type', models.ForeignKey(db_column='Id_type', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.type')),
            ],
            options={
                'db_table': 'Task',
                'managed': True,
                'unique_together': {('id_task', 'id_top', 'id_chap', 'id_conc_disc', 'id_disc')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='concretediscipline',
            unique_together={('id_conc_disc', 'id_disc')},
        ),
        migrations.CreateModel(
            name='Studentanswer',
            fields=[
                ('id_ans', models.AutoField(db_column='Id_ans', primary_key=True, serialize=False)),
                ('id_test', models.IntegerField(db_column='Id_test')),
                ('id_top', models.IntegerField(blank=True, db_column='Id_top', null=True)),
                ('id_chap', models.IntegerField(blank=True, db_column='Id_chap', null=True)),
                ('id_conc_disc', models.IntegerField(blank=True, db_column='Id_conc_disc', null=True)),
                ('id_disc', models.IntegerField(blank=True, db_column='Id_disc', null=True)),
                ('answer', models.CharField(blank=True, db_column='Answer', max_length=200, null=True)),
                ('id_res', models.ForeignKey(db_column='Id_res', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.result')),
                ('id_task', models.ForeignKey(db_column='Id_task', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.task')),
            ],
            options={
                'db_table': 'StudentAnswer',
                'managed': True,
                'unique_together': {('id_ans', 'id_res', 'id_test')},
            },
        ),
        migrations.CreateModel(
            name='Lectureranswer',
            fields=[
                ('id_ans', models.AutoField(db_column='Id_ans', primary_key=True, serialize=False)),
                ('is_right', models.BooleanField(db_column='Is_right')),
                ('id_top', models.IntegerField(db_column='Id_top')),
                ('id_chap', models.IntegerField(db_column='Id_chap')),
                ('id_conc_disc', models.IntegerField(db_column='Id_conc_disc')),
                ('id_disc', models.IntegerField(db_column='Id_disc')),
                ('answer', models.CharField(blank=True, db_column='Answer', max_length=200, null=True)),
                ('id_task', models.ForeignKey(db_column='Id_task', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.task')),
            ],
            options={
                'db_table': 'LecturerAnswer',
                'managed': True,
                'unique_together': {('id_ans', 'id_task', 'id_top', 'id_chap', 'id_conc_disc', 'id_disc')},
            },
        ),
        migrations.CreateModel(
            name='Tickettasks',
            fields=[
                ('id_tt', models.AutoField(db_column='Id_tt', primary_key=True, serialize=False)),
                ('id_top', models.IntegerField(db_column='Id_top')),
                ('id_chap', models.IntegerField(db_column='Id_chap')),
                ('id_conc_disc', models.IntegerField(db_column='Id_conc_disc')),
                ('id_disc', models.IntegerField(db_column='Id_disc')),
                ('value', models.IntegerField(blank=True, db_column='Value', null=True)),
                ('id_task', models.ForeignKey(db_column='Id_task', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.task')),
                ('id_tick', models.ForeignKey(db_column='Id_tick', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.ticket')),
            ],
            options={
                'db_table': 'TicketTasks',
                'managed': True,
                'unique_together': {('id_tt', 'id_tick', 'id_task', 'id_top', 'id_chap', 'id_conc_disc', 'id_disc')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('text', models.CharField(db_column='Text', max_length=500)),
                ('date_reg', models.DateField(db_column='Date_reg')),
                ('id_com', models.AutoField(db_column='Id_com', primary_key=True, serialize=False)),
                ('id_forum', models.ForeignKey(db_column='Id_forum', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.forum')),
                ('id_user', models.ForeignKey(db_column='Id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='site1.user')),
            ],
            options={
                'db_table': 'Comment',
                'managed': True,
                'unique_together': {('id_com', 'id_forum')},
            },
        ),
    ]
